import type { MemoryPostcard } from "./postcards";

export const memoryPostcards: MemoryPostcard[] = [
  // ── TOKYO ─────────────────────────────────────────────────────────
  {
    id: "koenji-vending-2am",
    coordinates: [35.7059, 139.6492],
    city: "tokyo",
    neighborhood: "Kōenji",
    streetHint: "somewhere near Kōenji north exit",
    fragmentType: "vending-machine",
    mood: "solitude",
    timeOfDay: "latenight",
    weather: "clear",
    title: "2am, Kōenji",
    caption: "The machine was the only light on the block.",
    memory: "Month four. I couldn't sleep, which was becoming a pattern. I walked for an hour without direction and found myself on a quiet street in Kōenji at 2am, in front of a vending machine that had no business being that warm. I got a Boss coffee. Hot, canned, a kind of thing that doesn't exist where I'm from.\n\nI stood there for probably ten minutes. No one walked past. The machine hummed. I hummed back a little, without thinking about it. I think that was the first time in Japan that I felt genuinely okay with being alone.",
    imageUrl: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800&q=75",
    imageAlt: "Quiet street at night, vending machine glow",
    author: "Anonymous",
    year: "2021",
    tags: ["2am", "vending-machine", "koenji", "walking"],
  },
  {
    id: "shimokitazawa-wrong-alley",
    coordinates: [35.6614, 139.6682],
    city: "tokyo",
    neighborhood: "Shimokitazawa",
    streetHint: "the alley behind the record shops, south side",
    fragmentType: "alley",
    mood: "wandering",
    timeOfDay: "afternoon",
    weather: "overcast",
    title: "The wrong alley",
    caption: "I got lost looking for the record shop. Again.",
    memory: "There's a record shop in Shimokitazawa I was trying to find for three Saturdays in a row. Each time I went down the wrong alley. The third alley had a coffee shop so small it had four seats. A dog sitting outside on its own. A sound system playing something from the 70s that I couldn't name.\n\nI gave up on the record shop that day. I stayed for two coffees. I still don't know what the song was. I've been back to that coffee shop four times and it's never been the same music.",
    imageUrl: "https://images.unsplash.com/photo-1520520731457-9283dd14aa66?w=800&q=75",
    imageAlt: "Narrow alley with small shops",
    year: "2019",
    tags: ["shimokitazawa", "alley", "lost", "music", "coffee"],
  },
  {
    id: "familymart-shinjuku-3am",
    coordinates: [35.6938, 139.7034],
    city: "tokyo",
    neighborhood: "Shinjuku",
    streetHint: "the FamilyMart near Kabukicho, east side",
    fragmentType: "konbini",
    mood: "invisible",
    timeOfDay: "latenight",
    weather: "clear",
    title: "FamilyMart, 3am",
    caption: "Four days. No real conversation.",
    memory: "I had gone four days without speaking to anyone beyond the automatic exchange — sumimasen, arigatou, sumimasen. The kind of language that moves you through a country without landing anywhere.\n\nI went to FamilyMart at 3am because my apartment felt too small to be lonely in. The cashier said ありがとうございました in that particular way, the exact same cadence every time. I stood at the door for a second too long because it was the most direct thing anyone had said to me in four days.\n\nI ate the onigiri on the curb. Nobody looked at me. In Japan, not being looked at is not the same as not being seen.",
    imageUrl: "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=75",
    imageAlt: "Convenience store interior, fluorescent light",
    year: "2023",
    tags: ["3am", "konbini", "shinjuku", "silence", "onigiri"],
  },
  {
    id: "train-crossing-ikebukuro",
    coordinates: [35.7295, 139.7109],
    city: "tokyo",
    neighborhood: "Ikebukuro",
    streetHint: "a side street east of the station, residential end",
    fragmentType: "train-crossing",
    mood: "restless",
    timeOfDay: "evening",
    weather: "overcast",
    title: "The crossing, Ikebukuro",
    caption: "The gate came down. I didn't move for three cycles.",
    memory: "There's a railway crossing on one of the narrow streets east of Ikebukuro. The barriers come down every six to eight minutes. I stood there and watched the gate lower, the Yamanote line pass, the gate rise, the cars inch forward — and then didn't cross.\n\nI did this three times. People walked around me. Nobody said anything. I was trying to figure out something I couldn't name — some decision I'd been postponing. The crossing kept offering me a chance to go. I kept not taking it.\n\nI eventually crossed on the fourth cycle. Whatever I'd been waiting to resolve hadn't resolved. But I crossed anyway.",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=75",
    imageAlt: "Railway crossing gate, evening light",
    year: "2022",
    tags: ["train-crossing", "ikebukuro", "waiting", "decision"],
  },
  {
    id: "arakawa-embankment-evening",
    coordinates: [35.7547, 139.8423],
    city: "tokyo",
    neighborhood: "Arakawa",
    streetHint: "the embankment path, north of Nishi-Arakawa station",
    fragmentType: "riverside",
    mood: "quiet",
    timeOfDay: "evening",
    weather: "clear",
    season: "autumn",
    title: "Arakawa, nobody else",
    caption: "Nobody walks here. That's why I walked here.",
    memory: "The Arakawa embankment in autumn has grass that turns a particular color — not quite gold, not brown. The river is wide and quiet and the walking path goes on for kilometers in each direction with almost no other people on it.\n\nI started coming here when I needed somewhere that didn't require me to perform. No eye contact to manage, no navigating the sidewalk choreography, no language. Just the grass and the river and the evening coming in from the east.\n\nI never told anyone about this place. Not out of selfishness — I just wanted one thing in Japan that was only mine for a while.",
    imageUrl: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=800&q=75",
    imageAlt: "River embankment path in autumn light",
    year: "2022",
    tags: ["arakawa", "river", "walking", "autumn", "alone"],
  },
  {
    id: "yanaka-staircase-cats",
    coordinates: [35.7264, 139.7680],
    city: "tokyo",
    neighborhood: "Yanaka",
    streetHint: "one of the old stone staircases off Yanaka Ginza",
    fragmentType: "staircase",
    mood: "wandering",
    timeOfDay: "afternoon",
    weather: "clear",
    title: "Staircase with cats",
    caption: "There is a staircase in Yanaka with a different cat on every third step.",
    memory: "I discovered this staircase by following someone who was following a cat. The first cat was tabby, sitting at the top. Halfway down there was an orange one sleeping across the step. At the bottom a black one that looked like it owned the whole street.\n\nThe staircase is old stone, worn in the middle. The buildings on either side have wooden planks and small potted plants and the kind of quiet order that only happens in neighborhoods that haven't been demolished.\n\nI went back twice to see if the cats were still there. Different cats, same steps. I think the cats are part of the infrastructure.",
    imageUrl: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?w=800&q=75",
    imageAlt: "Old stone staircase in quiet Tokyo neighborhood",
    year: "2019",
    tags: ["yanaka", "cats", "staircase", "old-tokyo"],
  },
  {
    id: "nakameguro-rain-umbrella",
    coordinates: [35.6406, 139.6980],
    city: "tokyo",
    neighborhood: "Nakameguro",
    streetHint: "the canal path, between two bridges",
    fragmentType: "sidewalk",
    mood: "tender",
    timeOfDay: "evening",
    weather: "rain",
    title: "Canal sidewalk, rain",
    caption: "She gave me her umbrella and walked to the station anyway.",
    memory: "I was standing under a narrow overhang waiting for the rain to ease when a woman — forties, office clothes, clearly going somewhere — stopped and held out her umbrella. My Japanese was still not good. I started to refuse. She just put it in my hand and kept walking.\n\nI stood there with the umbrella for a moment before I understood she'd given it to me. Not lent. Given.\n\nI left it at the information desk of the nearest station. I don't know if she got it back. I think about it sometimes when it rains.",
    imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&q=75",
    imageAlt: "Canal path at evening, wet pavement",
    year: "2020",
    tags: ["nakameguro", "rain", "umbrella", "kindness"],
  },
  {
    id: "koenji-laundromat-11pm",
    coordinates: [35.7065, 139.6510],
    city: "tokyo",
    neighborhood: "Kōenji",
    streetHint: "a side street off Kōenji Pal Shotengai",
    fragmentType: "laundromat",
    mood: "solitude",
    timeOfDay: "night",
    weather: "clear",
    title: "11pm laundromat",
    caption: "Three people. Three machines. No words.",
    memory: "I started using the 24-hour laundromat at 11pm because it was mostly empty. Over two months I found myself there on the same nights as a university student who always had the same red hoodie and an older man who always brought a book.\n\nWe never spoke. We rotated around each other — loading, moving to the dryers, folding in the corner. A domestic choreography without contact.\n\nAt the end of the month the old man finished folding, stood up, bowed slightly to both of us, and left. I bowed back. The student didn't look up but her posture changed in a way that felt like acknowledgment.",
    imageUrl: "https://images.unsplash.com/photo-1574871786514-46e1680ea587?w=800&q=75",
    imageAlt: "Fluorescent-lit interior at night, warm glow",
    year: "2021",
    tags: ["laundromat", "koenji", "night", "strangers", "routine"],
  },
  {
    id: "shimokitazawa-power-lines-dusk",
    coordinates: [35.6608, 139.6675],
    city: "tokyo",
    neighborhood: "Shimokitazawa",
    streetHint: "the residential streets north of the station",
    fragmentType: "utility-pole",
    mood: "adrift",
    timeOfDay: "evening",
    weather: "overcast",
    season: "summer",
    title: "Power lines, dusk",
    caption: "The wires went in every direction. I couldn't find north.",
    memory: "In the residential streets around Shimokitazawa the power lines run above everything — across, diagonal, down, connecting pole to pole to building to pole. They carry the neighbourhood above the pavement level, all the everyday infrastructure suspended overhead.\n\nI stood at an intersection at dusk trying to orient myself and looked up instead of at the map. The wires cut the sky into irregular sections. Swallows were landing and leaving from the cables.\n\nI'd been in Japan for seven months and still had the persistent low-level disorientation of someone who has not quite arrived. The power lines didn't help me find direction. But I looked at them for a long time and felt something loosen.",
    imageUrl: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=75",
    imageAlt: "Urban street at dusk, overhead wires and poles",
    year: "2019",
    tags: ["shimokitazawa", "power-lines", "dusk", "lost"],
  },
  {
    id: "harajuku-station-month-six",
    coordinates: [35.6702, 139.7027],
    city: "tokyo",
    neighborhood: "Harajuku",
    streetHint: "the quiet side exit of Harajuku station",
    fragmentType: "station-platform",
    mood: "anchored",
    timeOfDay: "morning",
    weather: "clear",
    season: "spring",
    title: "Harajuku, the other exit",
    caption: "Month six. I knew which exit without checking.",
    memory: "There's a version of arriving in a new country where every station is a problem — which exit, which direction, which platform. You check the map at every decision point. You plan two steps ahead. The city is a sequence of puzzles.\n\nAnd then, somewhere around month five or six, you stop checking. Your legs know which exit. Your body knows the timing of the gates. You stop translating the overhead announcements and start just listening to them as sound that tells you what to do.\n\nI noticed this one morning coming through the side exit at Harajuku. I hadn't thought about it at all. I was just walking.",
    imageUrl: "https://images.unsplash.com/photo-1535189043414-47a3c49a0bed?w=800&q=75",
    imageAlt: "Train station exit, morning commuters",
    year: "2019",
    tags: ["harajuku", "station", "routine", "arriving"],
  },

  // ── KYOTO ─────────────────────────────────────────────────────────
  {
    id: "kamo-river-stepping-stones-midnight",
    coordinates: [35.0116, 135.7681],
    city: "kyoto",
    neighborhood: "Sanjo riverside",
    streetHint: "the stepping stones near Sanjo bridge",
    fragmentType: "riverside",
    mood: "quiet",
    timeOfDay: "latenight",
    weather: "clear",
    season: "summer",
    title: "Stepping stones, midnight",
    caption: "The herons don't sleep.",
    memory: "There are stepping stones across the Kamo River near Sanjo. During the day families and couples cross them in both directions. At midnight they were empty.\n\nI crossed anyway. In both directions. Then sat on the bank for a long time watching the herons that stand in the shallows. One didn't move the entire time I was there — forty minutes or more. The city lights reflected in the moving water. The heron seemed to notice neither.\n\nI felt very small in a way that was comfortable.",
    imageUrl: "https://images.unsplash.com/photo-1493330551839-704f8fbd7e9b?w=800&q=75",
    imageAlt: "Kamo river at night, city reflections in water",
    year: "2021",
    tags: ["kamo-river", "midnight", "herons", "stepping-stones", "kyoto"],
  },
  {
    id: "gion-alley-before-tourists",
    coordinates: [35.0037, 135.7772],
    city: "kyoto",
    neighborhood: "Gion",
    streetHint: "Hanamikoji-dori before 7am",
    fragmentType: "alley",
    mood: "wandering",
    timeOfDay: "dawn",
    weather: "clear",
    title: "Gion, 6am",
    caption: "Before 7am, the street belongs to no one.",
    memory: "I had read: go to Gion early. I didn't know how early 'early' meant. I set my alarm for 5:45.\n\nAt 6am, Hanamikoji was empty. The lanterns were still lit at the tea houses, though the tea houses were closed. The wooden buildings had a quality in the early light — not theatrical, just present. They weren't performing history. They were just buildings where people still lived and worked.\n\nA woman in a housecoat came out of one of the machiya to sweep the step. She didn't acknowledge me. I stood very still. We occupied the same street on different terms, and both terms were valid.",
    imageUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=75",
    imageAlt: "Gion street in early morning light, empty",
    year: "2022",
    tags: ["gion", "dawn", "kyoto", "early-morning", "quiet"],
  },
  {
    id: "fushimi-small-cafe-afternoon",
    coordinates: [34.9671, 135.7727],
    city: "kyoto",
    neighborhood: "Fushimi",
    streetHint: "a side street off the main Fushimi road",
    fragmentType: "cafe",
    mood: "homesick",
    timeOfDay: "afternoon",
    weather: "overcast",
    season: "winter",
    title: "The small café, Fushimi",
    caption: "A song I didn't know, and I was sad for something I couldn't name.",
    memory: "The café had eight seats and was run by a man who looked like he'd been running it since before I was born. I ordered coffee by pointing. He put on a Japanese pop song from the 1980s.\n\nI don't know why it made me homesick. The song had nothing to do with anywhere I'd been. The café had nothing to do with anywhere I'd been. It might have been the overcast light, or the smell of old wood and coffee, or just that it was December and I'd been in Japan for ten months without going home.\n\nI sat there for an hour. He refilled my coffee twice without asking. I didn't cry. I came close.",
    imageUrl: "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=800&q=75",
    imageAlt: "Small local café interior, warm light",
    year: "2023",
    tags: ["fushimi", "café", "homesick", "winter", "music"],
  },
  {
    id: "fushimi-canal-bridge-dusk",
    coordinates: [34.9024, 135.7581],
    city: "kyoto",
    neighborhood: "Fushimi",
    streetHint: "one of the small canal bridges in south Fushimi",
    fragmentType: "bridge",
    mood: "tender",
    timeOfDay: "evening",
    weather: "clear",
    season: "spring",
    title: "The bridge, 6pm",
    caption: "He walked ahead. Then stopped and waited.",
    memory: "There's a small stone bridge over one of the narrow canals in Fushimi. I was crossing it in the evening when I noticed an elderly couple ahead of me — he was walking slightly faster, a pace or two ahead, the natural gap that forms between people who have been together long enough to stop synchronizing their stride.\n\nAt the midpoint of the bridge he stopped. Not because she had called him or touched his arm. He just stopped. She caught up. They stood together for a moment looking at the water and then walked on.\n\nI have thought about that gesture more times than seems proportionate. Something about the involuntary noticing. The stopping without being asked.",
    imageUrl: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=75",
    imageAlt: "Small bridge over canal at dusk, Kyoto",
    year: "2023",
    tags: ["fushimi", "bridge", "elderly-couple", "canal", "evening"],
  },
  {
    id: "kyoto-university-konbini-midnight",
    coordinates: [35.0262, 135.7809],
    city: "kyoto",
    neighborhood: "Yoshida",
    streetHint: "the konbini near Kyoto University east gate",
    fragmentType: "konbini",
    mood: "invisible",
    timeOfDay: "latenight",
    weather: "clear",
    title: "Midnight konbini, Yoshida",
    caption: "Three people. Three countries. The same fluorescent light.",
    memory: "Midnight at the konbini near Kyoto University. Three of us at the counter section, each on a laptop or phone, each eating the same cheap rice meal in individual trays. A student from Korea — I recognized the flag on her laptop sticker. A guy who I later found out was from Germany. Me.\n\nWe didn't speak. We shared the fluorescent light and the hum of the refrigeration units and the automatic doors opening and closing on nobody.\n\nAt some point the German guy looked up and said 'cold tonight' in English. We said yes. Then we went back to our screens. That was the full conversation. It was enough.",
    imageUrl: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=75",
    imageAlt: "Convenience store counter at midnight",
    year: "2022",
    tags: ["kyoto-university", "konbini", "midnight", "foreigners"],
  },

  // ── OSAKA ─────────────────────────────────────────────────────────
  {
    id: "dotonbori-intersection-rain",
    coordinates: [34.6687, 135.5005],
    city: "osaka",
    neighborhood: "Dotonbori",
    streetHint: "the intersection two streets south of the canal",
    fragmentType: "intersection",
    mood: "restless",
    timeOfDay: "night",
    weather: "rain",
    title: "Dotonbori, rain, no umbrella",
    caption: "Everyone knew exactly where they were going. I had been in Japan for two years.",
    memory: "I was at an intersection in the Dotonbori backstreets when the rain started. No umbrella. Around me, everyone else produced umbrellas from bags and continued walking as if the rain had been scheduled.\n\nI was in Japan at this point for two years, which I think of as the second crisis — not the initial overwhelm of arrival, but the second wave that comes when you've stopped being new. You've learned the surface. You still don't understand the depth.\n\nI walked in the rain for forty minutes. Got soaked. Felt better somehow. Bought a vending machine hot coffee in the rain. Stood under an overhang and drank it. Osaka lets you be like that.",
    imageUrl: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800&q=75",
    imageAlt: "Osaka night street, wet pavement reflecting lights",
    year: "2021",
    tags: ["dotonbori", "rain", "night", "osaka", "two-years"],
  },
  {
    id: "shinsekai-vending-machine-1am",
    coordinates: [34.6512, 135.5063],
    city: "osaka",
    neighborhood: "Shinsekai",
    streetHint: "the side streets behind Tsutenkaku Tower",
    fragmentType: "vending-machine",
    mood: "solitude",
    timeOfDay: "latenight",
    weather: "clear",
    title: "Hot coffee, ¥100, 1am",
    caption: "The best therapy I found in Japan cost ¥100.",
    memory: "I discovered the ¥100 hot coffee vending machines in Shinsekai at 1am, on one of those nights where walking seemed like the only option.\n\nThe canned coffee in Japan is its own particular thing — warmed in the machine, small enough to hold with both hands, slightly sweet, slightly industrial. There is no equivalent of it anywhere I've lived. It is food as comfort object rather than nutrition.\n\nI stood in front of that machine for twenty minutes. Bought three coffees. Drank two. Held the third until it was cold. Went home. Slept.",
    imageUrl: "https://images.unsplash.com/photo-1569518726634-a0b3e23a5a6a?w=800&q=75",
    imageAlt: "Night street, Shinsekai area, vending machine glow",
    year: "2020",
    tags: ["shinsekai", "vending-machine", "1am", "coffee", "walking"],
  },
  {
    id: "namba-backstreet-irasshaimase",
    coordinates: [34.6658, 135.5045],
    city: "osaka",
    neighborhood: "Namba",
    streetHint: "the narrow streets east of Dotonbori canal",
    fragmentType: "alley",
    mood: "belonging",
    timeOfDay: "afternoon",
    weather: "clear",
    title: "Namba, midday",
    caption: "Someone yelled irasshaimase and meant it.",
    memory: "This happens in Osaka in a way it doesn't happen in Tokyo: someone yells the welcome call at you and actually looks at you when they do it. Not the automatic greeting of a chain store, but the particular Osakan version which contains an invitation.\n\nI was walking through the Namba backstreets — the ones away from the canal, where the izakayas and ramen shops do a lunch service — when a man came out of his shop with a menu and held it toward me. Not aggressively. Just — here.\n\nI went in. It was noon. He brought me something without asking. It was excellent. He refilled my tea three times. I understood probably 60% of what he said. The 40% didn't seem to matter.",
    imageUrl: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&q=75",
    imageAlt: "Midday Osaka backstreet, small restaurant signs",
    year: "2021",
    tags: ["namba", "belonging", "osaka", "lunch", "welcome"],
  },
  {
    id: "okawa-river-bench-sunday",
    coordinates: [34.6906, 135.5163],
    city: "osaka",
    neighborhood: "Tenmabashi",
    streetHint: "the riverside path along the Okawa, east of the bridge",
    fragmentType: "park-bench",
    mood: "anchored",
    timeOfDay: "afternoon",
    weather: "clear",
    season: "spring",
    title: "The bench, Sunday afternoons",
    caption: "This bench. Every Sunday. Two years. Then I stopped needing it.",
    memory: "I found the bench on the Okawa riverside by accident in month three. It became a Sunday habit over the following two years — part ritual, part maintenance.\n\nThere was nothing special about it as a bench. Good view of the river. A food stand nearby that did taiyaki in winter. A recurring egret. Over time I watched the cherry blossoms come and go twice, watched the water level change with seasons, watched other regulars develop their own routines.\n\nIn month twenty-six I arrived on Sunday and realized I didn't need to be there. Not in the desperate way I had at first. I sat for a while anyway, out of affection rather than necessity. Then went home early.",
    imageUrl: "https://images.unsplash.com/photo-1493330551839-704f8fbd7e9b?w=800&q=75",
    imageAlt: "Riverside path, afternoon light on water",
    year: "2021",
    tags: ["okawa", "river", "osaka", "sunday", "routine"],
  },
  {
    id: "taisho-train-crossing-evening",
    coordinates: [34.6380, 135.4975],
    city: "osaka",
    neighborhood: "Taisho",
    streetHint: "an unmanned crossing in the Taisho residential streets",
    fragmentType: "train-crossing",
    mood: "quiet",
    timeOfDay: "evening",
    weather: "clear",
    season: "summer",
    title: "Train crossing, Taisho",
    caption: "The gate came down. Three people waited. Nobody checked their phones.",
    memory: "I had gotten on the wrong bus and ended up in Taisho ward at evening — a part of Osaka I'd never been, residential, quieter, many Vietnamese restaurants.\n\nI found myself at a small unmanned railway crossing. Three people waiting: an older woman with shopping bags, a man on a bicycle, a kid. When the alarm started and the barrier came down, all three just stood there. The woman adjusted her bags slightly. The man looked at the tracks.\n\nThe train came through — local, not express, unremarkable. The barrier rose. They crossed. I crossed with them.\n\nSomething about it felt like witnessing something private. Three people taking a small pause, together, without needing to acknowledge it was happening.",
    imageUrl: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=75",
    imageAlt: "Evening light on residential street, railway crossing",
    year: "2022",
    tags: ["taisho", "train-crossing", "evening", "ordinary", "osaka"],
  },
];
